const state={data:null,minutes:40,page:'focus',timer:null,selectedReward:null,selectedSpecies:null,plantMode:'basic',period:'all',catalogTier:'basic',systemStatus:null,recentContext:{notes:null,revision:0,editingId:null},nextAction:{active:null,pendingGeneration:false,pendingResponse:null,reportPath:null}};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const titles={focus:'开始专注','next-action':'下一步行动','recent-context':'近期动态',tasks:'任务清单',garden:'我的花园',rewards:'奖励记录',catalog:'植物图鉴',settings:'系统状态'};
const typeMeta={intervention_accepted:['介','主动接受系统介入'],intervention_basic:['介','介入累计初级奖励'],advanced_unlock:['高','初级植物累计高级奖励'],ai_help_completed:['AI','AI 建议完成闭环'],early_sleep:['眠','早睡估计达标'],focus_completed:['专','完成专注奖励']};
async function api(path,options={}){const res=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const text=await res.text();if(!text)throw new Error(`接口 ${path} 返回空响应`);let data;try{data=JSON.parse(text)}catch{throw new Error(`接口 ${path} 返回了非 JSON 数据`)}if(!res.ok){const error=new Error(data.error||`请求失败 (${res.status})`);error.payload=data;error.status=res.status;throw error}return data}
function toast(message,bad=false){const el=$('#toast');el.textContent=message;el.style.background=bad?'#8f3f39':'';el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),3000)}
function formatTime(value){if(!value)return'—';try{return new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value))}catch{return value}}
function catalogMap(){return Object.fromEntries(state.data.catalog.map(x=>[x.id,x]))}
function navigate(page){state.page=page;$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$$('.page').forEach(x=>x.classList.toggle('active',x.id===`page-${page}`));$('#pageTitle').textContent=titles[page];$('#sidebar').classList.remove('open');if(page==='garden')renderGarden();if(page==='next-action')loadNextActionPanel();if(page==='recent-context')loadRecentContext();if(page==='tasks')loadTasks();if(page==='settings')loadSystemStatus();}
function rewardMeta(type){return typeMeta[type]||['奖',type]}
function render(){const d=state.data,stats=d.stats;$('#focusMinutes').textContent=stats.focus_minutes;$('#plantCount').textContent=stats.planted;$('#pendingCount').textContent=d.pending_rewards.length;$('#creditText').textContent=`${stats.focus_credit_minutes} / 40`;$('#creditBar').style.width=`${stats.focus_credit_minutes/40*100}%`;$('#sleepCutoff').textContent=d.settings.early_sleep_cutoff;$('#coldTurkeyMode').textContent=d.settings.cold_turkey_mode==='live'?'正式锁定':'安全模拟';renderProfiles();renderFocus();renderFocusPlans();renderBridgeHealth();renderLatest();renderRewards();renderGarden();renderPlantingDock();renderCatalog();renderCounts()}
function renderProfiles(){const select=$('#profileSelect'),current=select.value;select.innerHTML=state.data.profiles.map(p=>`<option value="${p.id}">${p.name} · ${p.description}</option>`).join('');if(current)select.value=current}
function renderFocus(){clearInterval(state.timer);const focus=state.data.focus;const locked=Boolean(focus);$('#startBtn').classList.toggle('hidden',locked);$$('#presetRow button').forEach(b=>b.disabled=locked);$('#profileSelect').disabled=locked;if(!focus){$('#focusKicker').textContent='准备好种下一段专注了吗？';updateIdleTimer();return}$('#focusKicker').textContent=focus.task_title?`正在为「${focus.task_title}」安静生长。`:'专注正在生长，保持这一小片安静。';const tick=()=>{const seconds=Math.max(0,Math.ceil((new Date(focus.ends_at)-Date.now())/1000));$('#timerDisplay').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;if(seconds<=0){clearInterval(state.timer);setTimeout(load,2200)}};tick();state.timer=setInterval(tick,1000)}
function updateIdleTimer(){const m=state.minutes;$('#timerDisplay').textContent=`${String(m).padStart(2,'0')}:00`}
function renderFocusPlans(){const plans=state.data.focus_plans||[];$('#focusPlans').innerHTML=plans.length?plans.map(p=>{const phase=p.status==='break'?'休息中':p.status==='focus'?'第 '+p.current_round+' 轮专注中':'等待开始';const at=formatTime(p.next_action_at);return `<p>${p.kind==='cycle'?'连续':'预约'}：${p.focus_minutes} 分钟 × ${p.rounds} 轮 · ${phase} · ${at}</p>`}).join(''):'<p>没有待执行的预约或连续专注。</p>'}
function renderBridgeHealth(){const h=state.data.focus_bridge||{};if(h.state!=='stale'&&h.state!=='never')return;const key=`focus-bridge-notice-${h.last_seen_at||'never'}`;if(sessionStorage.getItem(key))return;sessionStorage.setItem(key,'1');toast(h.state==='never'?'手机 Focus Bridge 尚未建立心跳。请打开 App 并确认无障碍服务已启用。':'手机 Focus Bridge 心跳已暂停；下次手机解锁后打开 App 或重启无障碍服务。',true)}
function healthTone(value){return['active','ok','online','pass','qualified'].includes(value)?'ok':['inactive','failed','fail','stale','missing','never','degraded'].includes(value)?'bad':'warn'}
function healthAge(seconds){if(seconds===null||seconds===undefined)return'暂无时间';if(seconds<60)return'刚刚更新';if(seconds<3600)return`${Math.floor(seconds/60)} 分钟前`;return`${Math.floor(seconds/3600)} 小时前`}
function healthRow(label,value,detail=''){return`<div class="health-row"><i class="health-dot ${healthTone(value)}"></i><b>${escapeHtml(label)} · ${escapeHtml(value||'unknown')}</b><small>${escapeHtml(detail)}</small></div>`}
function renderSystemStatus(){const board=$('#systemStatusBoard'),summary=$('#systemStatusSummary'),s=state.systemStatus;if(!s){board.innerHTML='<article class="pixel-panel health-card wide"><p class="health-empty">等待健康数据…</p></article>';return}const services=(s.services||[]).map(x=>healthRow(x.name,x.state)).join('');const t=s.tasks||{},d=s.data||{},b=s.bridges||{};const taskRows=[healthRow('网页任务 queue',t.pending_mutation_count===0?'ok':`${t.pending_mutation_count} 条待写回`,t.revision===undefined?'未读取 revision':`revision ${t.revision}`),healthRow('Obsidian 快照',t.snapshot?.state,healthAge(t.snapshot?.age_seconds)),healthRow('同步检查',t.sync_heartbeat?.state,healthAge(t.sync_heartbeat?.age_seconds))].join('');const bridgeRows=[healthRow('Windows 介入 agent',b.windows?.state,healthAge(b.windows?.age_seconds)),healthRow('Android Focus Bridge',b.android?.state,healthAge(b.android?.age_seconds))].join('');const dataRows=[healthRow('行为上下文缓存',d.context_cache?.state,healthAge(d.context_cache?.age_seconds)),healthRow('最近半小时报告',d.latest_report?.state,healthAge(d.latest_report?.age_seconds)),healthRow('花园 SQLite 备份',d.archive_backup?.state,healthAge(d.archive_backup?.age_seconds))].join('');summary.textContent=`最后检查：${formatTime(s.generated_at)}。绿色表示正在运行或数据新鲜；红色表示陈旧、缺失或服务停止。`;board.innerHTML=`<article class="pixel-panel health-card wide"><p class="eyebrow">PI SERVICES</p><h3>Pi 核心服务</h3><div class="health-list">${services||'<p class="health-empty">未返回服务数据。</p>'}</div></article><article class="pixel-panel health-card"><p class="eyebrow">TASK SYNC</p><h3>任务与 Obsidian</h3><div class="health-list">${taskRows}</div></article><article class="pixel-panel health-card"><p class="eyebrow">DEVICE BRIDGES</p><h3>设备链路</h3><div class="health-list">${bridgeRows}</div></article><article class="pixel-panel health-card wide"><p class="eyebrow">DATA & RECOVERY</p><h3>数据与恢复</h3><div class="health-list">${dataRows}</div></article>`}
function renderSystemStatus(){const board=$('#systemStatusBoard'),summary=$('#systemStatusSummary'),s=state.systemStatus;if(!s){board.innerHTML='<article class="pixel-panel health-card wide"><p class="health-empty">等待健康数据…</p></article>';return}const services=(s.services||[]).map(x=>healthRow(x.name,x.state)).join('');const t=s.tasks||{},d=s.data||{},b=s.bridges||{},android=b.android||{},q=android.qualification||{};const taskRows=[healthRow('网页任务 queue',t.pending_mutation_count===0?'ok':`${t.pending_mutation_count} 条待写回`,t.revision===undefined?'未读取 revision':`revision ${t.revision}`),healthRow('Obsidian 快照',t.snapshot?.state,healthAge(t.snapshot?.age_seconds)),healthRow('同步检查',t.sync_heartbeat?.state,healthAge(t.sync_heartbeat?.age_seconds))].join('');const bridgeRows=[healthRow('Windows 介入 agent',b.windows?.state,healthAge(b.windows?.age_seconds)),healthRow('Android Focus Bridge',android.state,`${healthAge(android.age_seconds)}${q.app_version?' · v'+q.app_version:''}`)].join('');const qualificationRows=(q.checks||[]).map(check=>healthRow(check.label,check.state,check.detail)).join('');const dataRows=[healthRow('行为上下文缓存',d.context_cache?.state,healthAge(d.context_cache?.age_seconds)),healthRow('最近半小时报告',d.latest_report?.state,healthAge(d.latest_report?.age_seconds)),healthRow('花园 SQLite 备份',d.archive_backup?.state,healthAge(d.archive_backup?.age_seconds))].join('');summary.textContent=`最后检查：${formatTime(s.generated_at)}。绿色表示正在运行或数据新鲜；红色表示陈旧、缺失或服务停止。`;board.innerHTML=`<article class="pixel-panel health-card wide"><p class="eyebrow">PI SERVICES</p><h3>Pi 核心服务</h3><div class="health-list">${services||'<p class="health-empty">未返回服务数据。</p>'}</div></article><article class="pixel-panel health-card"><p class="eyebrow">TASK SYNC</p><h3>任务与 Obsidian</h3><div class="health-list">${taskRows}</div></article><article class="pixel-panel health-card"><p class="eyebrow">DEVICE BRIDGES</p><h3>设备链路</h3><div class="health-list">${bridgeRows}</div></article><article class="pixel-panel health-card wide"><p class="eyebrow">ANDROID BRIDGE ACCEPTANCE</p><h3>Focus Bridge 验收 · ${escapeHtml(q.label||'尚未验收')}</h3><p class="setting-help">${escapeHtml(q.summary||'等待新版状态协议。')}</p><div class="health-list">${qualificationRows||'<p class="health-empty">安装并启动 Focus Bridge 1.1.0 后开始累计验收证据。</p>'}</div></article><article class="pixel-panel health-card wide"><p class="eyebrow">DATA & RECOVERY</p><h3>数据与恢复</h3><div class="health-list">${dataRows}</div></article>`}
async function loadSystemStatus(){const summary=$('#systemStatusSummary');summary.textContent='正在检查 Pi 服务与数据新鲜度…';try{state.systemStatus=await api('/api/system-status');renderSystemStatus()}catch(error){state.systemStatus=null;renderSystemStatus();summary.textContent=`无法读取系统状态：${error.message}`;toast('系统状态读取失败',true)}}
function renderLatest(){const list=state.data.reward_history.slice(0,4);$('#latestRewards').innerHTML=list.length?list.map(r=>{const m=rewardMeta(r.type);return`<div class="mini-item"><span class="mini-icon">${m[0]}</span><div><p>${m[1]}</p><small>${formatTime(r.occurred_at)}</small></div></div>`}).join(''):'<p class="setting-help">同步后，奖励会出现在这里。</p>'}
function basicOpportunities(){return state.data.pending_rewards.filter(reward=>(reward.tier||'basic')==='basic')}
function renderPlantingDock(){const basic=basicOpportunities().length,advanced=Math.floor(basic/3);$('#basicPlantOpportunityCount').textContent=basic;$('#advancedPlantOpportunityCount').textContent=advanced;$('#plantBasicMenu').disabled=basic===0;$('#plantAdvancedMenu').disabled=advanced===0;$('#plantingDockHint').textContent=advanced?`已有 ${basic} 次初级机会；现在可消耗 3 次种植 1 株高级植物。`:`已积攒 ${basic} 次初级机会；再积攒 ${Math.max(0,3-basic)} 次即可种植高级植物。`}
function renderCounts(){const s=state.data.stats;$('#interventionProgress').textContent=`${s.intervention_progress||0} / 3`;$('#basicProgress').textContent=s.basic_available||0;$('#advancedAvailable').textContent=s.advanced_available||0;$('#tierPlantCount').textContent=`${s.basic_planted||0} / ${s.advanced_planted||0}`}
function renderRewards(){const list=state.data.reward_history;$('#rewardList').innerHTML=list.length?list.map(r=>{const m=rewardMeta(r.type),tier=r.tier==='advanced'?'高级':'初级';return`<div class="reward-row"><span class="reward-icon">${m[0]}</span><div><h3>${m[1]}</h3><p>${escapeHtml(r.reason)} · ${tier}植物资格</p></div><time>${formatTime(r.occurred_at)}</time>${r.status==='pending'?`<button class="plant-action" data-plant="${encodeURIComponent(r.id)}">领取${tier}植物</button>`:'<span class="planted-badge">✓ 已种植</span>'}</div>`}).join(''):'<div class="garden-empty"><h3>暂无可领取奖励</h3><p>主动接受 3 次介入后，会出现初级植物资格。</p></div>';$$('[data-plant]').forEach(b=>b.onclick=()=>openPlant(decodeURIComponent(b.dataset.plant)))}
function inPeriod(date,period){if(period==='all')return true;const d=new Date(date),now=new Date();if(period==='day')return d.toDateString()===now.toDateString();if(period==='year')return d.getFullYear()===now.getFullYear();if(period==='month')return d.getFullYear()===now.getFullYear()&&d.getMonth()===now.getMonth();if(period==='week'){const a=new Date(now);a.setHours(0,0,0,0);a.setDate(a.getDate()-((a.getDay()+6)%7));return d>=a}return true}
function renderGarden(){if(!state.data)return;const garden=state.data.garden,map=catalogMap(),plants=garden.plants.filter(p=>inPeriod(p.planted_at,state.period));const size=garden.size,r=size/2;$('#gardenSizeLabel').textContent=`${size} × ${size}`;$('#gardenPeriodLabel').textContent=({all:'全部种植记录',day:'今天',week:'本周',month:'本月',year:'今年'})[state.period];const byPos=Object.fromEntries(plants.map(p=>[`${p.x},${p.y}`,p]));let html='';for(let y=-Math.floor(r);y<=Math.floor(r);y++)for(let x=-Math.floor(r);x<=Math.floor(r);x++){const p=byPos[`${x},${y}`],species=p&&map[p.species_id];html+=`<div class="garden-tile">${p&&species?`<img src="/${species.sprite}" alt="${species.name}"><div class="tip"><b>${species.name}</b><br>${escapeHtml(p.reason)}<br>${formatTime(p.planted_at)}</div>`:''}</div>`}const grid=$('#gardenGrid');grid.style.gridTemplateColumns=`repeat(${size},1fr)`;grid.innerHTML=html;grid.classList.toggle('hidden',plants.length===0);$('#gardenEmpty').classList.toggle('hidden',plants.length!==0)}
function renderCatalog(){const names={flower:'花',tree:'树苗',mushroom:'蘑菇',decoration:'装饰'},tiers={basic:'初级',advanced:'高级'},tier=p=>p.tier==='advanced'?'advanced':'basic',selected=state.catalogTier==='advanced'?'advanced':'basic',basicCount=state.data.catalog.filter(p=>tier(p)==='basic').length,advancedCount=state.data.catalog.filter(p=>tier(p)==='advanced').length;$('#catalogTierTabs').innerHTML=`<button type="button" data-catalog-tier="basic" class="${selected==='basic'?'active':''}" role="tab" aria-selected="${selected==='basic'}">初级 <span>${basicCount}</span></button><button type="button" data-catalog-tier="advanced" class="${selected==='advanced'?'active':''}" role="tab" aria-selected="${selected==='advanced'}">高级 <span>${advancedCount}</span></button>`;$$('[data-catalog-tier]').forEach(button=>button.onclick=()=>{state.catalogTier=button.dataset.catalogTier;renderCatalog()});$('#catalogGrid').innerHTML=state.data.catalog.filter(p=>tier(p)===selected).map(p=>`<div class="catalog-card"><div class="sprite-box"><img src="/${p.sprite}" alt="${p.name}"></div><h3>${p.name}</h3><small>${tiers[tier(p)]} · ${names[p.category]||p.category} · ${p.id}</small></div>`).join('')}
function ensureGardenIsland(){const grid=$('#gardenGrid');let island=$('#gardenIsland');if(island)return island;island=document.createElement('div');island.id='gardenIsland';island.className='garden-island';grid.parentNode.insertBefore(island,grid);for(const cls of ['island-shadow','island-face island-face-left','island-face island-face-right']){const el=document.createElement('div');el.className=cls;island.appendChild(el)}grid.className='garden-top';island.appendChild(grid);const layer=document.createElement('div');layer.id='gardenPlants';layer.className='garden-plants';island.appendChild(layer);return island}
function renderGarden(){if(!state.data)return;const garden=state.data.garden,map=catalogMap(),plants=garden.plants.filter(p=>inPeriod(p.planted_at,state.period));const size=garden.size,offset=Math.floor(size/2),island=ensureGardenIsland();island.style.setProperty('--garden-size',size);$('#gardenSizeLabel').textContent=`${size} × ${size}`;$('#gardenPeriodLabel').textContent=({all:'全部种植记录',day:'今天',week:'本周',month:'本月',year:'今年'})[state.period];let tiles='';for(let row=0;row<size;row++)for(let col=0;col<size;col++){const left=50+(col-row-1)*50/size,top=(col+row)*50/size,unit=100/size;tiles+=`<div class="garden-tile" style="left:${left}%;top:${top}%;width:${unit}%;height:${unit}%"></div>`}$('#gardenGrid').innerHTML=tiles;$('#gardenPlants').innerHTML=plants.map(p=>{const species=map[p.species_id];if(!species)return'';const col=p.x+offset,row=p.y+offset,left=50+(col-row)*50/size,top=((col+row+1)*50/size)*.8065,z=100+col+row;return`<div class="garden-plant" style="left:${left}%;top:${top}%;z-index:${z}"><span class="plant-shadow"></span><img class="sprite-depth" src="/${species.sprite}" alt=""><img class="sprite-front" src="/${species.sprite}" alt="${escapeHtml(species.name)}"><div class="tip"><b>${escapeHtml(species.name)}</b><br>${escapeHtml(p.reason)}<br>${formatTime(p.planted_at)}</div></div>`}).join('');island.classList.toggle('is-empty',plants.length===0);$('#gardenEmpty').classList.toggle('hidden',plants.length!==0)}
function renderCubeGarden(){if(!state.data)return;const garden=state.data.garden,map=catalogMap(),plants=garden.plants.filter(p=>inPeriod(p.planted_at,state.period));const size=garden.size,offset=Math.floor(size/2),island=ensureGardenIsland(),logicalWidth=268*size+32,logicalHeight=134*size+164;island.classList.add('user-cube-garden');island.style.setProperty('--garden-size',size);island.style.aspectRatio=`${logicalWidth} / ${logicalHeight}`;$('#gardenSizeLabel').textContent=`${size} × ${size}`;$('#gardenPeriodLabel').textContent=({all:'全部种植记录',day:'今天',week:'本周',month:'本月',year:'今年'})[state.period];const byPos=Object.fromEntries(plants.map(p=>[`${p.x},${p.y}`,p]));let cells='';for(let row=0;row<size;row++)for(let col=0;col<size;col++){const left=134*(size-1+col-row)/logicalWidth*100,top=67*(col+row)/logicalHeight*100,width=300/logicalWidth*100,height=300/logicalHeight*100,p=byPos[`${col-offset},${row-offset}`],species=p&&map[p.species_id],plant=p&&species?`<div class="garden-plant" style="left:50%;top:22.34%"><span class="plant-shadow"></span><img class="sprite-depth" src="/${species.sprite}" alt=""><img class="sprite-front" src="/${species.sprite}" alt="${escapeHtml(species.name)}"><div class="tip"><b>${escapeHtml(species.name)}</b><br>${escapeHtml(p.reason)}<br>${formatTime(p.planted_at)}</div></div>`:'';cells+=`<div class="garden-cube-cell" style="left:${left}%;top:${top}%;width:${width}%;height:${height}%;z-index:${100+col+row}"><img class="garden-cube" src="/assets/blocks/grass_cube_user.png" alt="" aria-hidden="true">${plant}</div>`}$('#gardenGrid').innerHTML=cells;$('#gardenPlants').innerHTML='';island.classList.toggle('is-empty',plants.length===0);$('#gardenEmpty').classList.toggle('hidden',plants.length!==0)}
renderGarden=renderCubeGarden;
function ensurePlantCategoryTabs(){let tabs=$('#plantCategoryTabs');if(tabs)return tabs;tabs=document.createElement('div');tabs.id='plantCategoryTabs';tabs.className='plant-category-tabs';$('#plantPicker').before(tabs);return tabs}
function renderPlantCategory(tier){state.plantCategory=tier;state.selectedSpecies=null;$('#plantConfirm').disabled=true;const plantTier=p=>p.tier==='advanced'?'advanced':'basic',items=state.data.catalog.filter(p=>plantTier(p)===tier),label=tier==='advanced'?'高级':'初级',tabs=ensurePlantCategoryTabs();tabs.innerHTML=`<span class="plant-tier-lock">本次仅可领取${label}植物</span>`;$('#plantPicker').innerHTML=items.map(p=>`<button class="plant-option" data-species="${p.id}"><img src="/${p.sprite}" alt=""><span>${p.name}</span></button>`).join('');$$('[data-species]').forEach(button=>button.onclick=()=>{state.selectedSpecies=button.dataset.species;$$('[data-species]').forEach(item=>item.classList.toggle('selected',item===button));$('#plantConfirm').disabled=false})}
function openPlantTabbed(id){const reward=state.data.reward_history.find(r=>r.id===id);if(!reward)return;const tier=reward.tier==='advanced'?'advanced':'basic';state.plantMode='basic';state.selectedReward=id;state.selectedSpecies=null;$('#modalReason').textContent=`${reward.reason}（本次领取${tier==='advanced'?'高级':'初级'}植物）`;renderPlantCategory(tier);$('#plantModal').classList.remove('hidden')}
function openBasicPlanting(){const reward=basicOpportunities()[0];if(!reward){toast('暂时没有初级种植机会',true);return}openPlantTabbed(reward.id)}
function openAdvancedPlanting(){if(basicOpportunities().length<3){toast('需要积攒 3 次初级种植机会',true);return}state.plantMode='advanced-exchange';state.selectedReward=null;state.selectedSpecies=null;$('#modalReason').textContent='将消耗 3 次初级种植机会，兑换 1 次高级植物种植。';renderPlantCategory('advanced');$('#plantModal').classList.remove('hidden')}
openPlant=openPlantTabbed;
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function showNextActionLogin(show=true){$('#nextActionLogin').classList.toggle('hidden',!show)}
function nextActionStatus(message,bad=false){const el=$('#nextActionStatus');el.textContent=message;el.classList.toggle('bad',bad)}
function nextActionClarification(data){const value=data?.clarification||{};const rounds=Array.isArray(value.rounds)?value.rounds:[];return{rounds,maxRounds:Number(value.max_rounds)||2}}
function renderNextActionClarification(data){const {rounds,maxRounds}=nextActionClarification(data);const left=Math.max(0,maxRounds-rounds.length);const revision=Number(data.action_revision)||0;const accepted=data.accepted_action_revision!==undefined&&data.accepted_action_revision!==null;$('#nextActionAccept').disabled=accepted;$('#nextActionAccept').textContent=accepted?'已接受当前最后版本':(rounds.length?'接受最后更新的这一步':'开始这一步');$('#nextActionAcceptNote').textContent=accepted?`已接受行动版本 ${data.accepted_action_revision}；结束后请在下方记录结果。`:(rounds.length?`接受将记录第 ${rounds.length} 轮澄清后生成的行动版本 ${revision}；不会接受最初那一版。`:'如果你先说说卡点，接受只会指向最后生成的行动。');$('#nextActionClarify').disabled=accepted||left===0;$('#nextActionClarify').textContent=accepted?'已接受，等待结果':(left?`说说哪里卡住（还可 ${left} 轮）`:'已完成两轮澄清');$('#nextActionClarifyRound').textContent=`行动澄清 ${rounds.length}/${maxRounds}`;$('#nextActionClarifyHint').textContent=accepted?'当前行动已接受；请先记录结果，再生成新的建议。':(left?'写一句真实阻力；助手会给出更新后的行动。':'两轮已用完；现在可接受上方最后更新的一步，或换一个。');$('#nextActionClarifyHistory').innerHTML=rounds.length?rounds.map(item=>`<div class="next-action-dialogue"><p><b>你</b>${escapeHtml(item.user_message||'')}</p><p><b>助手</b>${escapeHtml(item.assistant_message||'')}</p></div>`).join(''):''}
function renderNextAction(data){state.nextAction.active=data;const evidence=Array.isArray(data.evidence_points)?data.evidence_points.slice(0,4):[];const card=$('#nextActionSuggestion');card.innerHTML=`<div class="next-action-title"><div><p class="eyebrow">A SMALL, REAL START</p><h2>${escapeHtml(data.title||'当前建议')}</h2></div><div class="next-action-pills"><span>${escapeHtml(data.duration_minutes||'')} 分钟</span><span>${escapeHtml(data.decision_type||'行动')}</span></div></div><div class="next-action-first-step"><span>当前最后版本 · 先做这一件</span><strong>${escapeHtml(data.first_step||'')}</strong></div><div class="next-action-copy"><h3>为什么是现在</h3><p>${escapeHtml(data.reason_short||'')}</p><p>${escapeHtml(data.persuasive_explanation||'')}</p></div><div class="next-action-evidence"><h3>花园看到的线索</h3>${evidence.length?`<ul>${evidence.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ul>`:'<p>这次没有可展示的线索。</p>'}</div><div class="next-action-reduced"><span>如果现在还是难</span><p>${escapeHtml(data.reduced_version||'')}</p></div>`;$('#nextActionFeedback').classList.toggle('hidden',!data.suggestion_id);if(data.suggestion_id)renderNextActionClarification(data);showNextActionLogin(false)}
function clearNextActionSuggestion(message='点击“为我找下一步”，或查看尚未结束的当前建议。'){state.nextAction.active=null;$('#nextActionSuggestion').innerHTML=`<div class="next-action-empty"><div class="empty-sprout">✦</div><h2>把今天的线索收拢成一步</h2><p>${escapeHtml(message)}</p></div>`;$('#nextActionFeedback').classList.add('hidden')}
async function loadNextActionActive(){try{renderNextAction(await api('/api/next-action/active'));nextActionStatus('当前建议会在这里安静等你。');return true}catch(error){if(error.status===404){clearNextActionSuggestion();return false}if(error.status===401){showNextActionLogin();nextActionStatus('请输入 Next Action 的访问密码后继续。');return false}nextActionStatus(error.message,true);return false}}
async function generateNextAction(exclude=''){nextActionStatus('正在整理此刻的线索，生成一条能开始的建议……');$('#nextActionGenerate').disabled=true;try{const data=await api('/api/next-action/generate',{method:'POST',body:JSON.stringify(exclude?{exclude_suggestion_id:exclude}:{})});state.nextAction.pendingGeneration=false;renderNextAction(data);nextActionStatus('这一步已经准备好，先只做第一步。')}catch(error){if(error.payload&&error.payload.code==='pending_outcome_required'){state.nextAction.pendingGeneration=true;renderNextAction(error.payload.suggestion);nextActionStatus('先记下上一条建议的结果；保存后会继续生成这一次。');return}if(error.status===401)showNextActionLogin();nextActionStatus(`生成失败：${error.message}`,true)}finally{$('#nextActionGenerate').disabled=false}}
async function saveNextActionResponse(result,withReason=false){const active=state.nextAction.active;if(!active)return;const body={result,expected_action_revision:Number(active.action_revision)||0};if(withReason){body.reason_code=$('#nextActionReason').value;body.detail=$('#nextActionDetail').value}try{const saved=await api(`/api/next-action/suggestion/${encodeURIComponent(active.suggestion_id)}/response`,{method:'POST',body:JSON.stringify(body)});$('#nextActionReasonBox').classList.add('hidden');if(result==='accepted'){active.accepted_action_revision=saved.accepted_action_revision;active.accepted_action_id=saved.accepted_action_id;renderNextAction(active)}nextActionStatus(withReason?'反馈已经存下，之后可以用来复盘。':(Number(active.action_revision)?'已接受最后更新的行动。':'已记下：开始。'));if(result==='alternative_requested')await generateNextAction(active.suggestion_id)}catch(error){nextActionStatus(error.message,true)}}
function openNextActionClarification(){const active=state.nextAction.active;if(!active)return;const {rounds,maxRounds}=nextActionClarification(active);if(rounds.length>=maxRounds){nextActionStatus('这条建议已经完成两轮澄清；请接受最后版本，或换一个。',true);return}$('#nextActionReasonBox').classList.add('hidden');$('#nextActionClarifyBox').classList.remove('hidden');$('#nextActionClarifyMessage').focus()}
async function submitNextActionClarification(){const active=state.nextAction.active;if(!active)return;const message=$('#nextActionClarifyMessage').value.trim();if(!message){nextActionStatus('先写一句你真正卡住的地方。',true);return}const button=$('#nextActionClarifySubmit');button.disabled=true;nextActionStatus('正在把这句阻力缩成更能开始的一步……');try{const data=await api(`/api/next-action/suggestion/${encodeURIComponent(active.suggestion_id)}/clarify`,{method:'POST',body:JSON.stringify({message,expected_action_revision:Number(active.action_revision)||0})});$('#nextActionClarifyMessage').value='';$('#nextActionClarifyBox').classList.add('hidden');renderNextAction(data);nextActionStatus('已更新为最后一版行动；“接受”只会接受这一步。')}catch(error){nextActionStatus(error.message,true)}finally{button.disabled=false}}
async function saveNextActionOutcome(result){const active=state.nextAction.active;if(!active)return;try{await api(`/api/next-action/suggestion/${encodeURIComponent(active.suggestion_id)}/outcome`,{method:'POST',body:JSON.stringify({result})});nextActionStatus(`已记录：${({completed:'完成了',still_doing:'正在做',not_started:'没开始'})[result]}。`);if(state.nextAction.pendingGeneration){state.nextAction.pendingGeneration=false;await generateNextAction()} }catch(error){nextActionStatus(error.message,true)}}
async function loginNextAction(){const password=$('#nextActionPassword').value;if(!password){nextActionStatus('请输入访问密码。',true);return}const button=$('#nextActionLoginBtn');button.disabled=true;try{await api('/api/next-action/login',{method:'POST',body:JSON.stringify({password})});$('#nextActionPassword').value='';showNextActionLogin(false);nextActionStatus('已解锁行动助手。');await loadNextActionPanel()}catch(error){nextActionStatus(error.message,true)}finally{button.disabled=false}}
async function loadNextActionReports(){try{const data=await api('/api/next-action/reports');const reports=Array.isArray(data.reports)?data.reports:[];$('#nextActionReportList').innerHTML=reports.length?reports.map(item=>`<button class="report-button" data-report-path="${encodeURIComponent(item.path)}">${escapeHtml(item.label||item.path)}</button>`).join(''):'<p class="setting-help">还没有可展示的报告。</p>';$$('[data-report-path]').forEach(button=>button.onclick=()=>loadNextActionReport(decodeURIComponent(button.dataset.reportPath)))}catch(error){if(error.status===401)showNextActionLogin();$('#nextActionReportList').innerHTML=`<p class="setting-help">${escapeHtml(error.message)}</p>`}}
async function loadNextActionReport(path){try{const data=await api(`/api/next-action/report?path=${encodeURIComponent(path)}`);state.nextAction.reportPath=path;$('#nextActionReportDetail').textContent=data.text||'报告为空。';$('#nextActionReportDetail').classList.remove('hidden');$('#nextActionReportFeedback').classList.remove('hidden')}catch(error){nextActionStatus(error.message,true)}}
async function submitNextActionReportFeedback(){if(!state.nextAction.reportPath){nextActionStatus('请先选择一条报告。',true);return}try{await api('/api/next-action/report-feedback',{method:'POST',body:JSON.stringify({category:$('#nextActionReportCategory').value,message:$('#nextActionReportMessage').value})});$('#nextActionReportMessage').value='';nextActionStatus('报告反馈已存档。')}catch(error){nextActionStatus(error.message,true)}}
async function loadNextActionIssues(){try{const data=await api('/api/next-action/issues');const issues=Array.isArray(data.issues)?data.issues:[];$('#nextActionIssueList').innerHTML=issues.length?issues.slice(0,4).map(item=>`<div><b>${escapeHtml(item.category||'问题')}</b><p>${escapeHtml(item.message||'')}</p></div>`).join(''):''}catch(error){if(error.status===401)showNextActionLogin()}}
async function submitNextActionIssue(){const message=$('#nextActionIssueMessage').value.trim();if(!message){nextActionStatus('先写下你遇到的问题。',true);return}try{await api('/api/next-action/issue-feedback',{method:'POST',body:JSON.stringify({category:$('#nextActionIssueCategory').value,severity:$('#nextActionIssueSeverity').value,message,page:'focus-garden-next-action',suggestion_id:state.nextAction.active?.suggestion_id||'',report_path:state.nextAction.reportPath||''})});$('#nextActionIssueMessage').value='';nextActionStatus('问题已收进 backlog。');await loadNextActionIssues()}catch(error){nextActionStatus(error.message,true)}}
function taskStatus(message,bad=false){const el=$('#taskStatus');el.textContent=message;el.classList.toggle('bad',bad)}
function taskId(){return `^${crypto.randomUUID().replace(/-/g,'').slice(0,8)}`}
function clearTaskForm(){state.nextAction.taskEditingId=null;$('#taskTitle').value='';$('#taskScheduledDate').value='';$('#taskDueDate').value='';$('#taskPriority').value='normal';$('#taskTomatoesTotal').value='';$('#taskSave').textContent='新建任务'}
function taskPayload(operation,taskIdValue){const total=$('#taskTomatoesTotal').value;return{operation,task_id:taskIdValue,title:$('#taskTitle').value.trim(),scheduled_date:$('#taskScheduledDate').value||null,due_date:$('#taskDueDate').value||null,priority:$('#taskPriority').value,tomatoes_total:total===''?null:Number(total)}}
function renderTasks(data){const groups=data.tasks||{},order=['unassigned','overdue','today','near_term','later','recurring'],meta={unassigned:['待正式安排','仅有重要等级；会写入 ToDo-任务集合顶部'],overdue:['已逾期','需要重新决定日期'],today:['今天','适合现在推进'],near_term:['未来三天','即将到来'],later:['之后','尚未到执行窗口'],recurring:['循环任务','请在 Obsidian 中维护完成']},items=order.flatMap(group=>(groups[group]||[]).map(task=>({...task,group})));state.nextAction.tasks=new Map(items.map(task=>[task.task_id,task]));$('#taskCount').textContent=`${items.length} 项待办`;const renderTask=task=>`<div class="task-row"><div class="task-row-copy"><b>${escapeHtml(task.title||'未命名任务')}</b><p>${escapeHtml(task.scheduled_date||'未安排')}<span>优先级：${escapeHtml(task.priority||'normal')}</span>${task.tomatoes_total!=null?`<span>🍅 ${escapeHtml(task.tomatoes_completed||0)}/${escapeHtml(task.tomatoes_total)}</span>`:''}</p></div><div class="task-row-actions"><button data-task-edit="${encodeURIComponent(task.task_id)}">编辑</button><button data-task-postpone="${encodeURIComponent(task.task_id)}">推迟一天</button>${task.recurrence?'':`<button class="danger" data-task-complete="${encodeURIComponent(task.task_id)}">完成</button>`}<button class="danger" data-task-delete="${encodeURIComponent(task.task_id)}">删除</button></div></div>`;$('#taskList').innerHTML=items.length?order.filter(group=>(groups[group]||[]).length).map(group=>`<section class="task-group"><div class="task-group-heading"><h3>${meta[group][0]}</h3><span>${meta[group][1]} · ${groups[group].length}</span></div>${groups[group].map(task=>renderTask({...task,group})).join('')}</section>`).join(''):'<div class="task-empty"><div>☷</div><h3>清单是空的</h3><p>在左侧写下下一件要做的事，或打开 Obsidian 同步已有任务。</p></div>';$$('[data-task-edit]').forEach(button=>button.onclick=()=>editTask(decodeURIComponent(button.dataset.taskEdit)));$$('[data-task-postpone]').forEach(button=>button.onclick=()=>postponeTask(decodeURIComponent(button.dataset.taskPostpone)));$$('[data-task-complete]').forEach(button=>button.onclick=()=>completeTask(decodeURIComponent(button.dataset.taskComplete)));$$('[data-task-delete]').forEach(button=>button.onclick=()=>deleteTask(decodeURIComponent(button.dataset.taskDelete)));taskStatus(data.pending_mutation_count?`Pi 有 ${data.pending_mutation_count} 条改动等待 Obsidian 写回。`:'已与 Pi 的有效任务视图同步。')}
async function loadTasks(){try{renderTasks(await api('/api/tasks'))}catch(error){taskStatus(error.message,true)}}
function editTask(id){const task=state.nextAction.tasks?.get(id);if(!task)return;state.nextAction.taskEditingId=id;$('#taskTitle').value=task.title||'';$('#taskScheduledDate').value=task.scheduled_date||'';$('#taskDueDate').value=task.due_date||'';$('#taskPriority').value=task.priority||'normal';$('#taskTomatoesTotal').value=task.tomatoes_total??'';$('#taskSave').textContent='保存修改';taskStatus(`正在编辑 ${id}。`)}
async function saveTask(){const id=state.nextAction.taskEditingId||taskId();if(!$('#taskTitle').value.trim()){taskStatus('请先写任务描述。',true);return}try{const operation=state.nextAction.taskEditingId?'update':'create';const result=await api('/api/tasks/mutations',{method:'POST',body:JSON.stringify(taskPayload(operation,id))});renderTasks(result.effective);clearTaskForm();taskStatus('已立即进入 Next Action；下次打开 Obsidian 会写回 Markdown。')}catch(error){taskStatus(error.message,true)}}
async function postponeTask(id){const task=state.nextAction.tasks?.get(id);if(!task)return;const current=new Date(`${task.scheduled_date||new Date().toISOString().slice(0,10)}T00:00:00`);current.setDate(current.getDate()+1);try{const result=await api('/api/tasks/mutations',{method:'POST',body:JSON.stringify({operation:'update',task_id:id,scheduled_date:current.toISOString().slice(0,10)})});renderTasks(result.effective);taskStatus('已推迟一天，并立即刷新 Next Action。')}catch(error){taskStatus(error.message,true)}}
async function completeTask(id){if(!confirm('将任务标记为完成并在下次打开 Obsidian 时归档到“已完成任务.md”。继续吗？'))return;try{const result=await api('/api/tasks/mutations',{method:'POST',body:JSON.stringify({operation:'complete',task_id:id})});renderTasks(result.effective);taskStatus('已标记完成，等待 Obsidian 归档。')}catch(error){taskStatus(error.message,true)}}
async function deleteTask(id){if(!confirm('删除后会在下次 Obsidian 同步时从任务 Markdown 移除，且无法自动恢复。继续吗？'))return;try{const result=await api('/api/tasks/mutations',{method:'POST',body:JSON.stringify({operation:'delete',task_id:id})});renderTasks(result.effective);taskStatus('已删除，等待 Obsidian 写回。')}catch(error){taskStatus(error.message,true)}}
function rcStatus(message,bad=false){const el=$('#rcStatus');el.textContent=message;el.classList.toggle('bad',bad)}
function rcGroupLabel(status){return status==='active'?'当前影响中':status==='upcoming'?'即将开始':status==='needs_review'?'需要确认':status==='conditional'?'条件性/待确认':status==='ended'?'已经过时':'已归档'}
function rcRow(note){
  const editable=!note.archived;
  const actions=[];
  actions.push(`<button data-rc-edit="${encodeURIComponent(note.id)}">编辑</button>`);
  if(editable&&!note.pinned)actions.push(`<button data-rc-pin="${encodeURIComponent(note.id)}">置顶</button>`);
  if(editable&&note.pinned)actions.push(`<button data-rc-unpin="${encodeURIComponent(note.id)}">取消置顶</button>`);
  if(editable&&(note.status==='conditional'||note.status==='needs_review'))actions.push(`<button data-rc-confirm="${encodeURIComponent(note.id)}">仍然相关</button>`);
  if(editable)actions.push(`<button data-rc-archive="${encodeURIComponent(note.id)}">归档</button>`);
  if(note.archived)actions.push(`<button data-rc-unarchive="${encodeURIComponent(note.id)}">恢复</button>`);
  const badges=[];
  if(note.pinned)badges.push('<span class="rc-badge rc-badge-pin">置顶</span>');
  if(note.status==='needs_review')badges.push('<span class="rc-badge rc-badge-review">需要确认</span>');
  if(note.status==='conditional')badges.push('<span class="rc-badge rc-badge-conditional">取决于外部事件</span>');
  return `<div class="rc-row"><div class="rc-row-copy"><b>${escapeHtml(note.content)}</b><p><span>记录时间：${formatTime(note.created_at)}</span><span>影响时段：${escapeHtml(note.impact_text||'未填写')}</span><span>系统理解：${escapeHtml(note.parse_text||'等待解析')}</span>${badges.join('')}</p></div><div class="rc-row-actions">${actions.join('')}</div></div>`;
}
function renderRecentContext(data){
  state.recentContext.notes=data.notes||[];
  state.recentContext.revision=data.revision;
  const groups={current:[],conditional:[],ended:[],archived:[]};
  (data.notes||[]).forEach(note=>{
    if(note.archived){groups.archived.push(note);return}
    if(note.status==='active'||note.status==='upcoming'){groups.current.push(note);return}
    if(note.status==='conditional'||note.status==='needs_review'){groups.conditional.push(note);return}
    groups.ended.push(note);
  });
  const section=(key,title,emptyText)=>`<section class="rc-group"><div class="rc-group-heading"><h3>${title}</h3><span>${groups[key].length}</span></div>${groups[key].length?groups[key].map(rcRow).join(''):`<p class="rc-empty">${emptyText}</p>`}</section>`;
  $('#rcLists').innerHTML=[
    section('current','当前及即将相关','还没有正在影响或即将开始的动态。'),
    section('conditional','需要确认','没有需要人工确认的动态。'),
    section('ended','已经过时','没有已过时的动态。已过时不会被删除，也不会进入 AI 判断。'),
    section('archived','已归档','没有已归档的动态。')
  ].join('');
  $$('[data-rc-edit]').forEach(b=>b.onclick=()=>editRecentContext(decodeURIComponent(b.dataset.rcEdit)));
  $$('[data-rc-pin]').forEach(b=>b.onclick=ev=>rcMutate(decodeURIComponent(b.dataset.rcPin),'pin',ev.currentTarget));
  $$('[data-rc-unpin]').forEach(b=>b.onclick=ev=>rcMutate(decodeURIComponent(b.dataset.rcUnpin),'unpin',ev.currentTarget));
  $$('[data-rc-confirm]').forEach(b=>b.onclick=ev=>rcMutate(decodeURIComponent(b.dataset.rcConfirm),'confirm',ev.currentTarget));
  $$('[data-rc-archive]').forEach(b=>b.onclick=ev=>rcMutate(decodeURIComponent(b.dataset.rcArchive),'archive',ev.currentTarget));
  $$('[data-rc-unarchive]').forEach(b=>b.onclick=ev=>rcMutate(decodeURIComponent(b.dataset.rcUnarchive),'unarchive',ev.currentTarget));
}
async function loadRecentContext(){try{renderRecentContext(await api('/api/recent-context'));rcStatus('已与 Pi 同步。')}catch(error){rcStatus(error.message,true)}}
function clearRecentContextForm(){state.recentContext.editingId=null;$('#rcContent').value='';$('#rcImpact').value='';$('#rcSave').textContent='记录'}
function editRecentContext(id){
  const note=(state.recentContext.notes||[]).find(n=>n.id===id);
  if(!note)return;
  state.recentContext.editingId=id;
  $('#rcContent').value=note.content;
  $('#rcImpact').value=note.impact_text||'';
  $('#rcSave').textContent='保存修改';
  rcStatus(`正在编辑 ${note.id}；保存时会用当前 revision 做冲突检测。`);
}
async function saveRecentContext(){
  const content=$('#rcContent').value.trim();
  if(!content){rcStatus('请先写动态内容。',true);return}
  const editing=state.recentContext.editingId;
  const button=$('#rcSave');button.disabled=true;
  const body={content,impact_text:$('#rcImpact').value.trim(),expected_revision:state.recentContext.revision};
  try{
    if(editing){
      await api(`/api/recent-context/${encodeURIComponent(editing)}/update`,{method:'POST',body:JSON.stringify(body)});
      rcStatus('修改已保存；系统正在重新解析影响时段。');
    }else{
      await api('/api/recent-context',{method:'POST',body:JSON.stringify(body)});
      rcStatus('已记录；系统正在解析影响时段。');
    }
    clearRecentContextForm();
    await loadRecentContext();
  }catch(error){
    if(error.status===409){
      // Keep the local draft; do NOT clear or overwrite.
      rcStatus('这条动态在别处刚被修改过。已刷新服务器版本，请确认后再保存。',true);
      await loadRecentContext();
    }else{
      rcStatus(`保存失败：${error.message}`,true);
    }
  }finally{button.disabled=false}
}
async function rcMutate(id,action,button){
  if(!button)return;button.disabled=true;
  try{
    await api(`/api/recent-context/${encodeURIComponent(id)}/${action}`,{method:'POST',body:JSON.stringify({expected_revision:state.recentContext.revision})});
    await loadRecentContext();
  }catch(error){
    if(error.status===409){rcStatus('内容刚被修改，已刷新版本，请重试。',true);await loadRecentContext()}
    else rcStatus(`${action} 失败：${error.message}`,true);
  }finally{button.disabled=false}
}
function renderNextActionContext(data){
  const items=(data.items||[]).slice(0,3);
  $('#nextActionContextList').innerHTML=items.length?items.map(item=>`<div class="rc-context-item"><p>${escapeHtml(item.content)}</p><small>影响时段：${escapeHtml(item.impact_text||'未填写')} · ${escapeHtml(item.parse_text||'')}</small></div>`).join(''):'<p class="setting-help">暂时没有需要纳入判断的近期动态。</p>';
}
async function loadNextActionContext(){try{renderNextActionContext(await api('/api/recent-context/relevant'))}catch(error){$('#nextActionContextList').innerHTML=`<p class="setting-help">${escapeHtml(error.message)}</p>`}}
async function loadNextActionPanel(){await loadNextActionActive();await Promise.all([loadNextActionReports(),loadNextActionIssues(),loadNextActionContext()])}
function openPlant(id){const reward=state.data.reward_history.find(r=>r.id===id);if(!reward)return;state.selectedReward=id;state.selectedSpecies=null;$('#modalReason').textContent=reward.reason;$('#plantConfirm').disabled=true;$('#plantPicker').innerHTML=state.data.catalog.map(p=>`<button class="plant-option" data-species="${p.id}"><img src="/${p.sprite}" alt=""><span>${p.name}</span></button>`).join('');$$('[data-species]').forEach(b=>b.onclick=()=>{state.selectedSpecies=b.dataset.species;$$('[data-species]').forEach(x=>x.classList.toggle('selected',x===b));$('#plantConfirm').disabled=false});$('#plantModal').classList.remove('hidden')}
function closePlant(){$('#plantModal').classList.add('hidden');state.selectedReward=null;state.selectedSpecies=null;state.plantMode='basic'}
function bindGardenPlantTips(){const grid=$('#gardenGrid');if(!grid)return;const closeAll=()=>$$('.garden-plant.is-tip-open').forEach(plant=>{plant.classList.remove('is-tip-open');plant.setAttribute('aria-expanded','false')});const toggle=plant=>{const open=plant.classList.contains('is-tip-open');closeAll();if(!open){plant.classList.add('is-tip-open');plant.setAttribute('aria-expanded','true')}};grid.addEventListener('click',event=>{const plant=event.target.closest('.garden-plant');if(plant){event.stopPropagation();toggle(plant)}else closeAll()});document.addEventListener('click',event=>{if(!event.target.closest('#gardenIsland'))closeAll()})}
async function plant(){try{$('#plantConfirm').disabled=true;const advanced=state.plantMode==='advanced-exchange';await api(advanced?'/api/rewards/advanced-plant':`/api/rewards/${encodeURIComponent(state.selectedReward)}/plant`,{method:'POST',body:JSON.stringify({species_id:state.selectedSpecies})});closePlant();await load();toast(advanced?'已消耗 3 次初级机会，种下高级植物！':'初级植物已经种下了');navigate('garden')}catch(e){toast(e.message,true);$('#plantConfirm').disabled=false}}
async function load(){state.data=await api('/api/bootstrap');render();if(state.page==='settings')loadSystemStatus()}
async function sync(){const btn=$('#syncBtn');btn.classList.add('loading');$('#syncText').textContent='同步中';try{const result=await api('/api/rewards/sync',{method:'POST',body:'{}'});await load();toast(result.inserted?`新增 ${result.inserted} 份奖励`:'奖励已是最新')}catch(e){toast(e.message,true)}finally{btn.classList.remove('loading');$('#syncText').textContent='同步奖励'}}
function bind(){$$('.nav-item').forEach(b=>b.onclick=()=>navigate(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go));$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#syncBtn').onclick=sync;$('#modalClose').onclick=closePlant;$('#plantModal').onclick=e=>{if(e.target.id==='plantModal')closePlant()};$('#plantConfirm').onclick=plant;$('#plantBasicMenu').onclick=openBasicPlanting;$('#plantAdvancedMenu').onclick=openAdvancedPlanting;$$('#presetRow button').forEach(b=>b.onclick=()=>{$$('#presetRow button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.minutes=Number(b.dataset.minutes);updateIdleTimer()});$$('.period-tabs button').forEach(b=>b.onclick=()=>{$$('.period-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.period=b.dataset.period;renderGarden()});$('#nextActionGenerate').onclick=()=>generateNextAction();$('#nextActionLoad').onclick=loadNextActionActive;$('#nextActionLoginBtn').onclick=loginNextAction;$('#nextActionAccept').onclick=()=>saveNextActionResponse('accepted');$('#nextActionClarify').onclick=openNextActionClarification;$('#nextActionClarifySubmit').onclick=submitNextActionClarification;$('#nextActionAlternative').onclick=()=>{$('#nextActionReasonBox').classList.remove('hidden');state.nextAction.pendingResponse='alternative_requested'};$('#nextActionDecline').onclick=()=>{$('#nextActionReasonBox').classList.remove('hidden');state.nextAction.pendingResponse='declined'};$('#nextActionReasonSubmit').onclick=()=>saveNextActionResponse(state.nextAction.pendingResponse,true);$$('[data-next-outcome]').forEach(button=>button.onclick=()=>saveNextActionOutcome(button.dataset.nextOutcome));$('#nextActionReportSubmit').onclick=submitNextActionReportFeedback;$('#nextActionIssueSubmit').onclick=submitNextActionIssue;$('#scheduleBtn').onclick=createSchedule;$('#cycleBtn').onclick=createContinuousFocus;$('#taskSave').onclick=saveTask;$('#taskClear').onclick=clearTaskForm;$('#taskRefresh').onclick=loadTasks;$('#rcSave').onclick=saveRecentContext;$('#rcRefresh').onclick=loadRecentContext}
bind();$('#systemStatusRefresh').onclick=loadSystemStatus;bindGardenPlantTips();load().then(()=>sync()).catch(e=>toast(e.message,true));

// The main action is deliberately dual-device.  Single-device execution is
// available only from the small "more" menu, never from shadow intervention.
state.targets=['windows','phone'];
state.focusTask=null;
function focusTargetLabel(){const labels={windows:'\u7535\u8111',phone:'\u624b\u673a'};return state.targets.length?state.targets.map(x=>labels[x]).join('\uff0b'):'\u4e0d\u9501\u673a'}
function setFocusTask(task){state.focusTask=task||null;const label=task?(task.title||'\u672a\u547d\u540d\u4efb\u52a1'):'\u4e0d\u5173\u8054\u4efb\u52a1';$('#focusTaskPicker').querySelector('span').textContent=label;$('#focusTaskPanel').classList.add('hidden')}
function focusTaskOptions(effective){const groups=effective?.tasks||{},items=['overdue','today','near_term','later','recurring'].flatMap(group=>groups[group]||[]);const seen=new Set(),chosen=[];for(const task of items){if(!task?.task_id||seen.has(task.task_id))continue;seen.add(task.task_id);chosen.push(task);if(chosen.length>=10)break}const list=$('#focusTaskList');if(!chosen.length){list.innerHTML='<p>\u6682\u65e0\u53ef\u5173\u8054\u7684\u5f85\u529e\u3002</p>';return}list.innerHTML=chosen.map(task=>`<button class="focus-task-choice" type="button" data-focus-task="${encodeURIComponent(task.task_id)}"><b>${escapeHtml(task.title||'\u672a\u547d\u540d\u4efb\u52a1')}</b><small>${task.tomatoes_total!=null?`\ud83c\udf45 ${task.tomatoes_completed||0}/${task.tomatoes_total}`:'\u672a\u8bbe \ud83c\udf45 \u9884\u4f30\uff0c\u4ec5\u8bb0\u5f55\u5173\u8054'}</small></button>`).join('');$$('[data-focus-task]').forEach(button=>button.onclick=()=>{const id=decodeURIComponent(button.dataset.focusTask);setFocusTask(chosen.find(task=>task.task_id===id)||null)})}
async function openFocusTaskPicker(){const panel=$('#focusTaskPanel');panel.classList.toggle('hidden');if(panel.classList.contains('hidden'))return;try{focusTaskOptions(await api('/api/tasks'))}catch(error){$('#focusTaskList').innerHTML=`<p>\u4efb\u52a1\u6682\u4e0d\u53ef\u7528\uff1a${escapeHtml(error.message)}</p>`}}
startFocusWithTargets=async function(){const duration=state.minutes,destination=focusTargetLabel(),task=state.focusTask,association=task?`\n\u5173\u8054\u4efb\u52a1\uff1a${task.title||'\u672a\u547d\u540d\u4efb\u52a1'}`:'\n\u4e0d\u5173\u8054\u4efb\u52a1',lockNote=state.targets.length?'\u5df2\u5f00\u59cb\u7684\u9501\u5b9a\u901a\u5e38\u65e0\u6cd5\u63d0\u524d\u89e3\u9664\u3002':'\u672c\u6b21\u4ec5\u8ba1\u65f6\uff0c\u4e0d\u4f1a\u9501\u5b9a\u8bbe\u5907\u3002';if(!confirm(`\u5c06\u5f00\u59cb ${duration} \u5206\u949f\u4e13\u6ce8\uff0c${destination}\u3002${association}\n${lockNote}\n\u662f\u5426\u7ee7\u7eed\uff1f`))return;try{$('#startBtn').disabled=true;await api('/api/focus/start',{method:'POST',body:JSON.stringify({duration,profile_id:$('#profileSelect').value,targets:state.targets,task_id:task?.task_id||null,task_title:task?.title||null,source:'garden'})});await load();toast(`\u4e13\u6ce8\u5df2\u5165\u56ed\uff1a${destination}${task?' \u00b7 \u5df2\u5173\u8054\u4efb\u52a1':''}`)}catch(error){toast(error.message,true)}finally{$('#startBtn').disabled=false}}
async function startFocusWithTargets(){
  const duration=state.minutes;
  const labels={windows:'电脑',phone:'手机'};
  const destination=state.targets.map(x=>labels[x]).join('＋');
  if(!confirm(`将开始 ${duration} 分钟专注，并介入：${destination}。已开始的锁定通常无法提前解除。是否继续？`))return;
  try{
    $('#startBtn').disabled=true;
    await api('/api/focus/start',{method:'POST',body:JSON.stringify({duration,profile_id:$('#profileSelect').value,targets:state.targets})});
    await load();toast(`专注已入队：${destination}`);
  }catch(error){toast(error.message,true)}finally{$('#startBtn').disabled=false}
}
async function createSchedule(){
  const raw=$('#scheduleAt').value;
  if(!raw){toast('请先选择预约开始时间',true);return}
  const startsAt=new Date(raw).toISOString();
  if(!confirm(`预约在 ${raw.replace('T',' ')} 开始 ${state.minutes} 分钟专注，并介入当前所选设备。是否继续？`))return;
  try{await api('/api/focus/schedule',{method:'POST',body:JSON.stringify({duration:state.minutes,profile_id:$('#profileSelect').value,targets:state.targets,starts_at:startsAt})});await load();toast('预约专注已创建')}catch(error){toast(error.message,true)}
}
async function createContinuousFocus(){
  const focusMinutes=Number($('#cycleFocusMinutes').value),restMinutes=Number($('#cycleRestMinutes').value),rounds=Number($('#cycleRounds').value);
  if(!confirm(`将开始 ${rounds} 轮：每轮专注 ${focusMinutes} 分钟，休息 ${restMinutes} 分钟。休息时不会解除已经开始的锁定。是否继续？`))return;
  try{await api('/api/focus/continuous',{method:'POST',body:JSON.stringify({focus_minutes:focusMinutes,rest_minutes:restMinutes,rounds,profile_id:$('#profileSelect').value,targets:state.targets})});await load();toast('连续专注已创建，第一轮即将开始')}catch(error){toast(error.message,true)}
}
$('#startBtn').onclick=startFocusWithTargets;
$('#targetMore').onclick=()=>$('#targetMenu').classList.toggle('hidden');
$('#focusTaskPicker').onclick=openFocusTaskPicker;
$('#focusTaskClear').onclick=()=>setFocusTask(null);
$$('[data-focus-target]').forEach(button=>button.onclick=()=>{
  state.targets=button.dataset.focusTarget?button.dataset.focusTarget.split(','):[];
  $('#targetMenu').classList.add('hidden');
  $('#startBtn').textContent=state.targets.length===2?'开始专注 · 电脑＋手机':`开始专注 · 仅${state.targets[0]==='windows'?'电脑':'手机'}`;
});
